// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PI_RouteBooks.Data;

#nullable disable

namespace PI_RouteBooks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PI_RouteBooks.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdComentario");

                    b.HasIndex("PostId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Curtida", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("curtidas", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPost"));

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CategoriaEspecifica")
                        .HasColumnType("longtext");

                    b.Property<int>("CategoriasIdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext");

                    b.Property<string>("Resumo")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEspecifico")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPostagem")
                        .HasColumnType("longtext");

                    b.Property<int>("TiposIdTipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuariosIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdPost");

                    b.HasIndex("CategoriasIdCategoria");

                    b.HasIndex("TiposIdTipo");

                    b.HasIndex("UsuariosIdUsuario");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("poststags", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Seguidor", b =>
                {
                    b.Property<int>("IdSeguidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_seguidor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSeguidor"));

                    b.Property<DateTime>("DataSeguimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_seguimento");

                    b.Property<int>("IdUsuarioSeguido")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_seguido");

                    b.Property<int>("IdUsuarioSeguidor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_seguidor");

                    b.HasKey("IdSeguidor");

                    b.HasIndex("IdUsuarioSeguido");

                    b.HasIndex("IdUsuarioSeguidor");

                    b.ToTable("seguidores", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Tag", b =>
                {
                    b.Property<int>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tag");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTag"));

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("IdTag");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Tipo", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdTipo");

                    b.ToTable("tipos", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("alterado_em");

                    b.Property<string>("Biografia")
                        .HasColumnType("longtext")
                        .HasColumnName("biografia");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataFimSuspensao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fim_suspensao");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("EstadoConta")
                        .HasColumnType("longtext")
                        .HasColumnName("estado_conta");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext")
                        .HasColumnName("pais");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("uf");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Comentario", b =>
                {
                    b.HasOne("PI_RouteBooks.Models.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PI_RouteBooks.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Curtida", b =>
                {
                    b.HasOne("PI_RouteBooks.Models.Post", "Post")
                        .WithMany("Curtidas")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PI_RouteBooks.Models.Usuario", "Usuario")
                        .WithMany("Curtidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Post", b =>
                {
                    b.HasOne("PI_RouteBooks.Models.Categoria", "CategoriaRef")
                        .WithMany()
                        .HasForeignKey("CategoriasIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PI_RouteBooks.Models.Tipo", "TipoRef")
                        .WithMany("Posts")
                        .HasForeignKey("TiposIdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PI_RouteBooks.Models.Usuario", "Autor")
                        .WithMany("Posts")
                        .HasForeignKey("UsuariosIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("CategoriaRef");

                    b.Navigation("TipoRef");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.PostTag", b =>
                {
                    b.HasOne("PI_RouteBooks.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PI_RouteBooks.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Seguidor", b =>
                {
                    b.HasOne("PI_RouteBooks.Models.Usuario", "UsuarioSeguido")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSeguido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PI_RouteBooks.Models.Usuario", "UsuarioSeguidor")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSeguidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioSeguido");

                    b.Navigation("UsuarioSeguidor");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Post", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Tag", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Tipo", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PI_RouteBooks.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
